export type {
  IClickUpList,
  ICollection,
  ICollectionBreakdown,
  INotionDatabase,
  IReportInsights,
  IReportQuery,
  IReportSegment,
  IReportSession,
  IReportSummary,
  IReportTopTask,
  IStatusMapping,
  ITask,
  ITimeSession,
  ITimelinePoint,
  IUser,
  TaskStatus,
} from "@linkdo/shared";
